# Compile the latex source to PDF and add it to the repo.

name: Compile-LateX
 
on:
  # Run on pushes into the main branch
  push:
    branches:
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Compile LateX
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Compile book and cover PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          main.tex
    - name: Move generated PDF files into out/
      run: mkdir -p out && mv main.pdf out/
    # Upload generated PDFs to repo.
    - name: Commit cover and main PDFs to repo
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'automatically updated by workflow action'
        push-branch: 'main'
        force-add: 'true'
        files: out/main.pdf
        name: 'auto'
        email: 'noreply@noreply.org'
