# Compile the latex source to PDF and add it to the repo.

name: Compile-LateX
 
on:
  # Run after the Super-Linter completes
  workflow_run:
   workflows: ["Super-Linter"]
   branches: [ main ]
   types: [ completed ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Compile LateX
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Confirm prior workflows OK
      uses: ahmadnassri/action-workflow-run-wait@v1
    - name: Compile book and cover PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          tex/cover.tex
          tex/main.tex
    - name: Move generated PDF files into pdf/
      run: mkdir -p pdf && mv cover.pdf main.pdf pdf/
    # Upload generated PDFs to repo.
    - name: Commit cover and main PDFs to repo
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'automatically updated by workflow action'
        push-branch: 'main'
        force-add: 'true'
        files: pdf/cover.pdf pdf/main.pdf
        name: 'auto'
        email: 'noreply@noreply.org'
